- name: install ansible
  pip:
    name: 'ansible==2.2.0.0'

- name: install ansible playbook
  copy:
    src: update_dns.yml
    dest: /root/update_dns.yml

- name: set cron
  cron:
    name: update dns
    special_time: reboot
    user: root
    job: /usr/local/bin/ansible-playbook /root/update_dns.yml -v > /var/log/update_dns.log
