- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: get_ip
      uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
        return_content: yes
      register: global_ip

    - name: set A record
      route53:
        command: create
        zone: kikusu.net
        record: github-jenkins.kikusu.net
        type: A
        ttl: 300
        value: "{{ global_ip.content }}"
        overwrite: yes
